name: WhitelistPlus
version: 1.0.0
main: com.kamillapinski.whitelistplus.WhitelistPlusPlugin
description: A simple whitelist plugin for Minecraft
author: Kamil Łapiński
api-version: 1.19
load: STARTUP
website: https://kampillapinski.com

commands:
  whp-reload:
    description: Reloads the whitelist
    usage: /whp-reload
    permission: whitelistplus.reload
  whp-kick:
    description: Kick all non-whitelisted players
    usage: /whp-kick
    permission: whitelistplus.kick